### ISSUE TITLE
Shortdump SYNTAX_ERROR

### ISSUE THREAD

**Issue by nomssi** [marcellourbani/abap_debugger_object_graph_extension#2]
Category               ABAP programming error
Runtime Errors         SYNTAX_ERROR
ABAP Program           ZCL_DEBUG_OBJ_TO_GRAPH========CP
Application Component  Not assigned
Date and Time          11.09.2018 04:35:49

In method DISPLAY_GRAPH( ), the object type ZCL_ABAP_GRAPH is unknown.

**Comment by nomssi** [comment]
fixed by installing ABAP Graph.

**Comment by marcellourbani** [comment]
Should have been clear in README, fixed
